### FOR MOVIES ###

GET http://localhost:3000/movies
###
POST http://localhost:3000/movies
content-type: application/json

{
  "title": "test",
  "year": 1880,
  "plot": "test",
  "director": "hellaur"
}
###
GET http://localhost:3000/movies/31
###
PATCH http://localhost:3000/movies/31
content-type: application/json

{
  "director": "James Cameron",
  "title": "Titanic"
}
###
DELETE http://localhost:3000/movies/30
###

# ###
# GET http://localhost:3000/random_movie
# ###
# GET http://localhost:3000/by_letter?l=A
# ###
# GET http://localhost:3000/search/titANIC
# ###

### FOR ACTORS ###

GET http://localhost:3000/actors.json
###
POST http://localhost:3000/actors.json
content-type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "known_for": "test",
  "age": 14,
  "gender": "feMale",
  "movie_id": 26
}
###
GET http://localhost:3000/actors/15.json
###
PATCH http://localhost:3000/actors/15.json
content-type: application/json

{
  "known_for": "something, probably",
  "age": 16,
  "gender": "maLE",
  "movie_id": 27
}
###
DELETE http://localhost:3000/actors/16

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}