### FOR MOVIES ###

GET http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDkzNTkyOTJ9.Uw7FilUO-SEiyyI5yjF5o4kegkiboQAo5FMWZSp3OwE
###
POST http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDkzNTkyOTJ9.Uw7FilUO-SEiyyI5yjF5o4kegkiboQAo5FMWZSp3OwE
content-type: application/json

{
  "title": "squeaker2",
  "year": 1880,
  "plot": "test",
  "director": "hellaur"
}
###
GET http://localhost:3000/movies/33
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDkzNTkyOTJ9.Uw7FilUO-SEiyyI5yjF5o4kegkiboQAo5FMWZSp3OwE
###
PATCH http://localhost:3000/movies/31
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2MDY3Njl9.mHCrxPS0igqHgsJ7LZ1SgKZ8IpdPWbvaNYBQJ2B3C5o
content-type: application/json

{
  "director": "James Cameron",
  "title": "Titanic"
}
###
DELETE http://localhost:3000/movies/30
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2MDY3Njl9.mHCrxPS0igqHgsJ7LZ1SgKZ8IpdPWbvaNYBQJ2B3C5o
###

# ###
# GET http://localhost:3000/random_movie
# ###
# GET http://localhost:3000/by_letter?l=A
# ###
# GET http://localhost:3000/search/titANIC
# ###

### FOR ACTORS ###

GET http://localhost:3000/actors.json
###
POST http://localhost:3000/actors.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDkzNTkyMjl9.AsZPYVZViTeRCbt3_pZzyUpC8EaS7VBhStG0XBJOHr0
content-type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "known_for": "test",
  "age": 14,
  "gender": "feMale",
  "movie_id": 26
}
###
GET http://localhost:3000/actors/15.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2MDY3Njl9.mHCrxPS0igqHgsJ7LZ1SgKZ8IpdPWbvaNYBQJ2B3C5o
###
PATCH http://localhost:3000/actors/15.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2MDY3Njl9.mHCrxPS0igqHgsJ7LZ1SgKZ8IpdPWbvaNYBQJ2B3C5o
content-type: application/json

{
  "known_for": "something, probably",
  "age": 16,
  "gender": "maLE",
  "movie_id": 27
}
###
DELETE http://localhost:3000/actors/15
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2MDY3Njl9.mHCrxPS0igqHgsJ7LZ1SgKZ8IpdPWbvaNYBQJ2B3C5o
###

### FOR USERS ###
POST http://localhost:3000/users.json
Content-Type: application/json

# {
#   "name": "Test name",
#   "email": "test@test.com",
#   "password": "password",
#   "password_confirmation": "password"
# }

{
  "name": "origa",
  "email": "origa@grams.com",
  "password": "auspex",
  "password_confirmation": "auspex"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

# {
#   "email": "test@test.com",
#   "password": "password"
# }

{
  "email": "origa@grams.com",
  "password": "auspex"
}

###

### FOR MOVIE GENRES ###

POST http://localhost:3000/movie_genres.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2MDY3Njl9.mHCrxPS0igqHgsJ7LZ1SgKZ8IpdPWbvaNYBQJ2B3C5o
Content-Type: application/json

{
  "movie_id": 27,
  "genre_id": 1
}

###